### ISSUE TITLE
The settings for AudioIPC Server are not remembered

### ISSUE THREAD

**Issue by pd3** [rhaas80/pa_volume#3]
First of all, thanks for the great app!! It works great for all sorts of applications, but unfortunately not with Firefox.

While playing (for example a youtube video) I can change the volume with `pa_volume 'AudioIPC Server' 40` and it works. Unfortunately, the setting is not remembered (or is changed by something) so that next time it is played the volume will be at 100% again. 

The intended usage is not youtube of course, there I adjust the volume manually, but messaging apps. Their notifications are way too loud and the volume cannot be adjusted. Is there a way how to get around this problem?

**Comment by rhaas80** [comment]
I gave this a try and indeed "AudioIPC server"'s volume level does not stay where one sets it using pa_volume. For an actual YouTube video the volume is reset by Firefox since YouTube remembers the volume setting that you chose in the UI in the browser and restores that one for the next video. This seems like the correct thing to do to me (and there is nothing I can do about that).
For message notification sounds (which I cannot test so easily) you may be able to change Firefox's default volume setting in:
```
about:config
```
then search for ```media.default_volume``` (see eg https://askubuntu.com/questions/908262/firefox-starts-in-mute-by-default).
The issue is that all sound from Firefox is seens as coming from "AudioIPC server" with no way for pulseaudio to distinguish between eg videos and notifications.

**Comment by pd3** [comment]
This seems like the correct solution. Thank you!

**Comment by gerroon** [comment]
This does not work for me, Youtube in Firefox still insanely loud :(

**Comment by rhaas80** [comment]
@gerroon can you provide more details about what behaviour your observed, please? You should also keep in mind the description provided https://github.com/rhaas80/pa_volume/issues/3#issuecomment-452743601 , namely that changing the YouTube volume only in PulseAudio (either via a GUI of `pa_volume`) is never remembered since YouTube itself resets it when the video starts playing. You have to use the volume control in the YouTube player to have the change "stick".
